package com.sistema.model.bean;
// Generated 23/11/2017 10:36:54 by Hibernate Tools 4.3.1



/**
 * Admsistema generated by hbm2java
 */
public class Admsistema  implements java.io.Serializable {


     private Integer admcod;
     private String admlogin;
     private int admsenha;
     private String tipouser;

    public Admsistema() {
    }

	
    public Admsistema(String admlogin, int admsenha) {
        this.admlogin = admlogin;
        this.admsenha = admsenha;
    }
    public Admsistema(String admlogin, int admsenha, String tipouser) {
       this.admlogin = admlogin;
       this.admsenha = admsenha;
       this.tipouser = tipouser;
    }
   
    public Integer getAdmcod() {
        return this.admcod;
    }
    
    public void setAdmcod(Integer admcod) {
        this.admcod = admcod;
    }
    public String getAdmlogin() {
        return this.admlogin;
    }
    
    public void setAdmlogin(String admlogin) {
        this.admlogin = admlogin;
    }
    public int getAdmsenha() {
        return this.admsenha;
    }
    
    public void setAdmsenha(int admsenha) {
        this.admsenha = admsenha;
    }
    public String getTipouser() {
        return this.tipouser;
    }
    
    public void setTipouser(String tipouser) {
        this.tipouser = tipouser;
    }




}


