package com.sistema.model.bean;
// Generated 23/11/2017 10:36:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private Integer empcod;
     private String empnome;
     private String empcnpj;
     private Set funcionarios = new HashSet(0);
     private Set funcionarios_1 = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(String empnome, String empcnpj) {
        this.empnome = empnome;
        this.empcnpj = empcnpj;
    }
    public Empresa(String empnome, String empcnpj, Set funcionarios, Set funcionarios_1) {
       this.empnome = empnome;
       this.empcnpj = empcnpj;
       this.funcionarios = funcionarios;
       this.funcionarios_1 = funcionarios_1;
    }
   
    public Integer getEmpcod() {
        return this.empcod;
    }
    
    public void setEmpcod(Integer empcod) {
        this.empcod = empcod;
    }
    public String getEmpnome() {
        return this.empnome;
    }
    
    public void setEmpnome(String empnome) {
        this.empnome = empnome;
    }
    public String getEmpcnpj() {
        return this.empcnpj;
    }
    
    public void setEmpcnpj(String empcnpj) {
        this.empcnpj = empcnpj;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }
    public Set getFuncionarios_1() {
        return this.funcionarios_1;
    }
    
    public void setFuncionarios_1(Set funcionarios_1) {
        this.funcionarios_1 = funcionarios_1;
    }




}


