package com.sistema.model.bean;
// Generated 23/11/2017 10:36:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Enfermeiro generated by hbm2java
 */
public class Enfermeiro  implements java.io.Serializable {


     private Integer enfcod;
     private String enfcpf;
     private int enfsenham;
     private String enfloginm;
     private String enfnome;
     private String enfrg;
     private int enfcoren;
     private String tipouser;
     private Set triagems = new HashSet(0);

    public Enfermeiro() {
    }

	
    public Enfermeiro(String enfcpf, int enfsenham, String enfloginm, String enfnome, String enfrg, int enfcoren) {
        this.enfcpf = enfcpf;
        this.enfsenham = enfsenham;
        this.enfloginm = enfloginm;
        this.enfnome = enfnome;
        this.enfrg = enfrg;
        this.enfcoren = enfcoren;
    }
    public Enfermeiro(String enfcpf, int enfsenham, String enfloginm, String enfnome, String enfrg, int enfcoren, String tipouser, Set triagems) {
       this.enfcpf = enfcpf;
       this.enfsenham = enfsenham;
       this.enfloginm = enfloginm;
       this.enfnome = enfnome;
       this.enfrg = enfrg;
       this.enfcoren = enfcoren;
       this.tipouser = tipouser;
       this.triagems = triagems;
    }
   
    public Integer getEnfcod() {
        return this.enfcod;
    }
    
    public void setEnfcod(Integer enfcod) {
        this.enfcod = enfcod;
    }
    public String getEnfcpf() {
        return this.enfcpf;
    }
    
    public void setEnfcpf(String enfcpf) {
        this.enfcpf = enfcpf;
    }
    public int getEnfsenham() {
        return this.enfsenham;
    }
    
    public void setEnfsenham(int enfsenham) {
        this.enfsenham = enfsenham;
    }
    public String getEnfloginm() {
        return this.enfloginm;
    }
    
    public void setEnfloginm(String enfloginm) {
        this.enfloginm = enfloginm;
    }
    public String getEnfnome() {
        return this.enfnome;
    }
    
    public void setEnfnome(String enfnome) {
        this.enfnome = enfnome;
    }
    public String getEnfrg() {
        return this.enfrg;
    }
    
    public void setEnfrg(String enfrg) {
        this.enfrg = enfrg;
    }
    public int getEnfcoren() {
        return this.enfcoren;
    }
    
    public void setEnfcoren(int enfcoren) {
        this.enfcoren = enfcoren;
    }
    public String getTipouser() {
        return this.tipouser;
    }
    
    public void setTipouser(String tipouser) {
        this.tipouser = tipouser;
    }
    public Set getTriagems() {
        return this.triagems;
    }
    
    public void setTriagems(Set triagems) {
        this.triagems = triagems;
    }




}


