package com.sistema.model.bean;
// Generated 23/11/2017 16:10:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Especialidade generated by hbm2java
 */
public class Especialidade  implements java.io.Serializable {


     private Integer espcod;
     private String espdesc;
     private Set medicos = new HashSet(0);

    public Especialidade() {
    }

    public Especialidade(String espdesc, Set medicos) {
       this.espdesc = espdesc;
       this.medicos = medicos;
    }
   
    public Integer getEspcod() {
        return this.espcod;
    }
    
    public void setEspcod(Integer espcod) {
        this.espcod = espcod;
    }
    public String getEspdesc() {
        return this.espdesc;
    }
    
    public void setEspdesc(String espdesc) {
        this.espdesc = espdesc;
    }
    public Set getMedicos() {
        return this.medicos;
    }
    
    public void setMedicos(Set medicos) {
        this.medicos = medicos;
    }




}


