package com.sistema.model.bean;
// Generated 23/11/2017 10:36:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Exame generated by hbm2java
 */
public class Exame  implements java.io.Serializable {


     private Integer exacod;
     private String exadesc;
     private Set consultas = new HashSet(0);

    public Exame() {
    }

	
    public Exame(String exadesc) {
        this.exadesc = exadesc;
    }
    public Exame(String exadesc, Set consultas) {
       this.exadesc = exadesc;
       this.consultas = consultas;
    }
   
    public Integer getExacod() {
        return this.exacod;
    }
    
    public void setExacod(Integer exacod) {
        this.exacod = exacod;
    }
    public String getExadesc() {
        return this.exadesc;
    }
    
    public void setExadesc(String exadesc) {
        this.exadesc = exadesc;
    }
    public Set getConsultas() {
        return this.consultas;
    }
    
    public void setConsultas(Set consultas) {
        this.consultas = consultas;
    }




}


