package com.sistema.model.bean;
// Generated 23/11/2017 16:10:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Exame generated by hbm2java
 */
public class Exame  implements java.io.Serializable {


     private Integer exacod;
     private String exadesc;
     private Set solicitacaos = new HashSet(0);

    public Exame() {
    }

	
    public Exame(String exadesc) {
        this.exadesc = exadesc;
    }
    public Exame(String exadesc, Set solicitacaos) {
       this.exadesc = exadesc;
       this.solicitacaos = solicitacaos;
    }
   
    public Integer getExacod() {
        return this.exacod;
    }
    
    public void setExacod(Integer exacod) {
        this.exacod = exacod;
    }
    public String getExadesc() {
        return this.exadesc;
    }
    
    public void setExadesc(String exadesc) {
        this.exadesc = exadesc;
    }
    public Set getSolicitacaos() {
        return this.solicitacaos;
    }
    
    public void setSolicitacaos(Set solicitacaos) {
        this.solicitacaos = solicitacaos;
    }




}


