package com.sistema.model.bean;
// Generated 23/11/2017 10:36:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private Integer funcod;
     private Empresa empresa;
     private String funcpf;
     private String funlogin;
     private int funsenha;
     private String funnome;
     private String funrg;
     private String tipouser;
     private Set empresas = new HashSet(0);

    public Funcionario() {
    }

	
    public Funcionario(Empresa empresa, String funcpf, String funlogin, int funsenha, String funnome, String funrg) {
        this.empresa = empresa;
        this.funcpf = funcpf;
        this.funlogin = funlogin;
        this.funsenha = funsenha;
        this.funnome = funnome;
        this.funrg = funrg;
    }
    public Funcionario(Empresa empresa, String funcpf, String funlogin, int funsenha, String funnome, String funrg, String tipouser, Set empresas) {
       this.empresa = empresa;
       this.funcpf = funcpf;
       this.funlogin = funlogin;
       this.funsenha = funsenha;
       this.funnome = funnome;
       this.funrg = funrg;
       this.tipouser = tipouser;
       this.empresas = empresas;
    }
   
    public Integer getFuncod() {
        return this.funcod;
    }
    
    public void setFuncod(Integer funcod) {
        this.funcod = funcod;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getFuncpf() {
        return this.funcpf;
    }
    
    public void setFuncpf(String funcpf) {
        this.funcpf = funcpf;
    }
    public String getFunlogin() {
        return this.funlogin;
    }
    
    public void setFunlogin(String funlogin) {
        this.funlogin = funlogin;
    }
    public int getFunsenha() {
        return this.funsenha;
    }
    
    public void setFunsenha(int funsenha) {
        this.funsenha = funsenha;
    }
    public String getFunnome() {
        return this.funnome;
    }
    
    public void setFunnome(String funnome) {
        this.funnome = funnome;
    }
    public String getFunrg() {
        return this.funrg;
    }
    
    public void setFunrg(String funrg) {
        this.funrg = funrg;
    }
    public String getTipouser() {
        return this.tipouser;
    }
    
    public void setTipouser(String tipouser) {
        this.tipouser = tipouser;
    }
    public Set getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set empresas) {
        this.empresas = empresas;
    }




}


