package com.sistema.model.bean;
// Generated 23/11/2017 16:10:36 by Hibernate Tools 4.3.1



/**
 * Gerente generated by hbm2java
 */
public class Gerente  implements java.io.Serializable {


     private Integer gercod;
     private Empresa empresa;
     private String gercpf;
     private int gersenha;
     private String gernome;
     private String gerlogin;
     private String gerrg;
     private String tipouser;

    public Gerente() {
    }

	
    public Gerente(Empresa empresa, String gercpf, int gersenha, String gernome, String gerlogin, String gerrg) {
        this.empresa = empresa;
        this.gercpf = gercpf;
        this.gersenha = gersenha;
        this.gernome = gernome;
        this.gerlogin = gerlogin;
        this.gerrg = gerrg;
    }
    public Gerente(Empresa empresa, String gercpf, int gersenha, String gernome, String gerlogin, String gerrg, String tipouser) {
       this.empresa = empresa;
       this.gercpf = gercpf;
       this.gersenha = gersenha;
       this.gernome = gernome;
       this.gerlogin = gerlogin;
       this.gerrg = gerrg;
       this.tipouser = tipouser;
    }
   
    public Integer getGercod() {
        return this.gercod;
    }
    
    public void setGercod(Integer gercod) {
        this.gercod = gercod;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getGercpf() {
        return this.gercpf;
    }
    
    public void setGercpf(String gercpf) {
        this.gercpf = gercpf;
    }
    public int getGersenha() {
        return this.gersenha;
    }
    
    public void setGersenha(int gersenha) {
        this.gersenha = gersenha;
    }
    public String getGernome() {
        return this.gernome;
    }
    
    public void setGernome(String gernome) {
        this.gernome = gernome;
    }
    public String getGerlogin() {
        return this.gerlogin;
    }
    
    public void setGerlogin(String gerlogin) {
        this.gerlogin = gerlogin;
    }
    public String getGerrg() {
        return this.gerrg;
    }
    
    public void setGerrg(String gerrg) {
        this.gerrg = gerrg;
    }
    public String getTipouser() {
        return this.tipouser;
    }
    
    public void setTipouser(String tipouser) {
        this.tipouser = tipouser;
    }




}


