package com.sistema.model.bean;
// Generated 23/11/2017 16:10:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Medico generated by hbm2java
 */
public class Medico  implements java.io.Serializable {


     private Integer medcod;
     private Empresa empresa;
     private String medcpf;
     private String medlogin;
     private int medsenha;
     private String mednome;
     private String medrg;
     private int medcrm;
     private String tipouser;
     private Set consultas = new HashSet(0);
     private Set especialidades = new HashSet(0);

    public Medico() {
    }

	
    public Medico(Empresa empresa, String medcpf, String medlogin, int medsenha, String mednome, String medrg, int medcrm) {
        this.empresa = empresa;
        this.medcpf = medcpf;
        this.medlogin = medlogin;
        this.medsenha = medsenha;
        this.mednome = mednome;
        this.medrg = medrg;
        this.medcrm = medcrm;
    }
    public Medico(Empresa empresa, String medcpf, String medlogin, int medsenha, String mednome, String medrg, int medcrm, String tipouser, Set consultas, Set especialidades) {
       this.empresa = empresa;
       this.medcpf = medcpf;
       this.medlogin = medlogin;
       this.medsenha = medsenha;
       this.mednome = mednome;
       this.medrg = medrg;
       this.medcrm = medcrm;
       this.tipouser = tipouser;
       this.consultas = consultas;
       this.especialidades = especialidades;
    }
   
    public Integer getMedcod() {
        return this.medcod;
    }
    
    public void setMedcod(Integer medcod) {
        this.medcod = medcod;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getMedcpf() {
        return this.medcpf;
    }
    
    public void setMedcpf(String medcpf) {
        this.medcpf = medcpf;
    }
    public String getMedlogin() {
        return this.medlogin;
    }
    
    public void setMedlogin(String medlogin) {
        this.medlogin = medlogin;
    }
    public int getMedsenha() {
        return this.medsenha;
    }
    
    public void setMedsenha(int medsenha) {
        this.medsenha = medsenha;
    }
    public String getMednome() {
        return this.mednome;
    }
    
    public void setMednome(String mednome) {
        this.mednome = mednome;
    }
    public String getMedrg() {
        return this.medrg;
    }
    
    public void setMedrg(String medrg) {
        this.medrg = medrg;
    }
    public int getMedcrm() {
        return this.medcrm;
    }
    
    public void setMedcrm(int medcrm) {
        this.medcrm = medcrm;
    }
    public String getTipouser() {
        return this.tipouser;
    }
    
    public void setTipouser(String tipouser) {
        this.tipouser = tipouser;
    }
    public Set getConsultas() {
        return this.consultas;
    }
    
    public void setConsultas(Set consultas) {
        this.consultas = consultas;
    }
    public Set getEspecialidades() {
        return this.especialidades;
    }
    
    public void setEspecialidades(Set especialidades) {
        this.especialidades = especialidades;
    }




}


