package com.sistema.model.bean;
// Generated 23/11/2017 16:10:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Paciente generated by hbm2java
 */
public class Paciente  implements java.io.Serializable {


     private Integer paccod;
     private String pacnome;
     private String pacrg;
     private String paccpf;
     private String tipouser;
     private Set quadroclinicos = new HashSet(0);
     private Set triagems = new HashSet(0);
     private Set consultas = new HashSet(0);

    public Paciente() {
    }

	
    public Paciente(String pacnome, String pacrg, String paccpf) {
        this.pacnome = pacnome;
        this.pacrg = pacrg;
        this.paccpf = paccpf;
    }
    public Paciente(String pacnome, String pacrg, String paccpf, String tipouser, Set quadroclinicos, Set triagems, Set consultas) {
       this.pacnome = pacnome;
       this.pacrg = pacrg;
       this.paccpf = paccpf;
       this.tipouser = tipouser;
       this.quadroclinicos = quadroclinicos;
       this.triagems = triagems;
       this.consultas = consultas;
    }
   
    public Integer getPaccod() {
        return this.paccod;
    }
    
    public void setPaccod(Integer paccod) {
        this.paccod = paccod;
    }
    public String getPacnome() {
        return this.pacnome;
    }
    
    public void setPacnome(String pacnome) {
        this.pacnome = pacnome;
    }
    public String getPacrg() {
        return this.pacrg;
    }
    
    public void setPacrg(String pacrg) {
        this.pacrg = pacrg;
    }
    public String getPaccpf() {
        return this.paccpf;
    }
    
    public void setPaccpf(String paccpf) {
        this.paccpf = paccpf;
    }
    public String getTipouser() {
        return this.tipouser;
    }
    
    public void setTipouser(String tipouser) {
        this.tipouser = tipouser;
    }
    public Set getQuadroclinicos() {
        return this.quadroclinicos;
    }
    
    public void setQuadroclinicos(Set quadroclinicos) {
        this.quadroclinicos = quadroclinicos;
    }
    public Set getTriagems() {
        return this.triagems;
    }
    
    public void setTriagems(Set triagems) {
        this.triagems = triagems;
    }
    public Set getConsultas() {
        return this.consultas;
    }
    
    public void setConsultas(Set consultas) {
        this.consultas = consultas;
    }




}


