package com.sistema.model.bean;
// Generated 23/11/2017 16:10:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Receita generated by hbm2java
 */
public class Receita  implements java.io.Serializable {


     private Integer reccod;
     private String recdesco;
     private Set consultas = new HashSet(0);

    public Receita() {
    }

	
    public Receita(String recdesco) {
        this.recdesco = recdesco;
    }
    public Receita(String recdesco, Set consultas) {
       this.recdesco = recdesco;
       this.consultas = consultas;
    }
   
    public Integer getReccod() {
        return this.reccod;
    }
    
    public void setReccod(Integer reccod) {
        this.reccod = reccod;
    }
    public String getRecdesco() {
        return this.recdesco;
    }
    
    public void setRecdesco(String recdesco) {
        this.recdesco = recdesco;
    }
    public Set getConsultas() {
        return this.consultas;
    }
    
    public void setConsultas(Set consultas) {
        this.consultas = consultas;
    }




}


