package com.sistema.model.bean;
// Generated 23/11/2017 16:10:36 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Solicitacao generated by hbm2java
 */
public class Solicitacao  implements java.io.Serializable {


     private SolicitacaoId id;
     private Consulta consulta;
     private Exame exame;
     private Date soldata;

    public Solicitacao() {
    }

    public Solicitacao(SolicitacaoId id, Consulta consulta, Exame exame, Date soldata) {
       this.id = id;
       this.consulta = consulta;
       this.exame = exame;
       this.soldata = soldata;
    }
   
    public SolicitacaoId getId() {
        return this.id;
    }
    
    public void setId(SolicitacaoId id) {
        this.id = id;
    }
    public Consulta getConsulta() {
        return this.consulta;
    }
    
    public void setConsulta(Consulta consulta) {
        this.consulta = consulta;
    }
    public Exame getExame() {
        return this.exame;
    }
    
    public void setExame(Exame exame) {
        this.exame = exame;
    }
    public Date getSoldata() {
        return this.soldata;
    }
    
    public void setSoldata(Date soldata) {
        this.soldata = soldata;
    }




}


