package com.sistema.model.bean;
// Generated 23/11/2017 10:36:54 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Triagem generated by hbm2java
 */
public class Triagem  implements java.io.Serializable {


     private Integer tricod;
     private Enfermeiro enfermeiro;
     private Paciente paciente;
     private Date tridata;

    public Triagem() {
    }

    public Triagem(Enfermeiro enfermeiro, Paciente paciente, Date tridata) {
       this.enfermeiro = enfermeiro;
       this.paciente = paciente;
       this.tridata = tridata;
    }
   
    public Integer getTricod() {
        return this.tricod;
    }
    
    public void setTricod(Integer tricod) {
        this.tricod = tricod;
    }
    public Enfermeiro getEnfermeiro() {
        return this.enfermeiro;
    }
    
    public void setEnfermeiro(Enfermeiro enfermeiro) {
        this.enfermeiro = enfermeiro;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public Date getTridata() {
        return this.tridata;
    }
    
    public void setTridata(Date tridata) {
        this.tridata = tridata;
    }




}


